// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: src/taskTracker.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetTaskNameRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskId string `protobuf:"bytes,1,opt,name=TaskId,proto3" json:"TaskId,omitempty"`
}

func (x *GetTaskNameRequest) Reset() {
	*x = GetTaskNameRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_taskTracker_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTaskNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskNameRequest) ProtoMessage() {}

func (x *GetTaskNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_taskTracker_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskNameRequest.ProtoReflect.Descriptor instead.
func (*GetTaskNameRequest) Descriptor() ([]byte, []int) {
	return file_src_taskTracker_proto_rawDescGZIP(), []int{0}
}

func (x *GetTaskNameRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type GetTaskNameResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskName string `protobuf:"bytes,1,opt,name=TaskName,proto3" json:"TaskName,omitempty"`
}

func (x *GetTaskNameResponse) Reset() {
	*x = GetTaskNameResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_taskTracker_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTaskNameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskNameResponse) ProtoMessage() {}

func (x *GetTaskNameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_taskTracker_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskNameResponse.ProtoReflect.Descriptor instead.
func (*GetTaskNameResponse) Descriptor() ([]byte, []int) {
	return file_src_taskTracker_proto_rawDescGZIP(), []int{1}
}

func (x *GetTaskNameResponse) GetTaskName() string {
	if x != nil {
		return x.TaskName
	}
	return ""
}

var File_src_taskTracker_proto protoreflect.FileDescriptor

var file_src_taskTracker_proto_rawDesc = []byte{
	0x0a, 0x15, 0x73, 0x72, 0x63, 0x2f, 0x74, 0x61, 0x73, 0x6b, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x65,
	0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x74, 0x61, 0x73, 0x6b, 0x54, 0x72, 0x61,
	0x63, 0x6b, 0x65, 0x72, 0x22, 0x2c, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x4e,
	0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x54, 0x61,
	0x73, 0x6b, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x54, 0x61, 0x73, 0x6b,
	0x49, 0x64, 0x22, 0x31, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x4e, 0x61, 0x6d,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x54, 0x61, 0x73,
	0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x54, 0x61, 0x73,
	0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x32, 0x61, 0x0a, 0x0b, 0x54, 0x61, 0x73, 0x6b, 0x54, 0x72, 0x61,
	0x63, 0x6b, 0x65, 0x72, 0x12, 0x52, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x1f, 0x2e, 0x74, 0x61, 0x73, 0x6b, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x65,
	0x72, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x74, 0x61, 0x73, 0x6b, 0x54, 0x72, 0x61, 0x63, 0x6b,
	0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x0a, 0x5a, 0x08, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_src_taskTracker_proto_rawDescOnce sync.Once
	file_src_taskTracker_proto_rawDescData = file_src_taskTracker_proto_rawDesc
)

func file_src_taskTracker_proto_rawDescGZIP() []byte {
	file_src_taskTracker_proto_rawDescOnce.Do(func() {
		file_src_taskTracker_proto_rawDescData = protoimpl.X.CompressGZIP(file_src_taskTracker_proto_rawDescData)
	})
	return file_src_taskTracker_proto_rawDescData
}

var file_src_taskTracker_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_src_taskTracker_proto_goTypes = []interface{}{
	(*GetTaskNameRequest)(nil),  // 0: taskTracker.GetTaskNameRequest
	(*GetTaskNameResponse)(nil), // 1: taskTracker.GetTaskNameResponse
}
var file_src_taskTracker_proto_depIdxs = []int32{
	0, // 0: taskTracker.TaskTracker.GetTaskName:input_type -> taskTracker.GetTaskNameRequest
	1, // 1: taskTracker.TaskTracker.GetTaskName:output_type -> taskTracker.GetTaskNameResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_src_taskTracker_proto_init() }
func file_src_taskTracker_proto_init() {
	if File_src_taskTracker_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_src_taskTracker_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTaskNameRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_taskTracker_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTaskNameResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_src_taskTracker_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_src_taskTracker_proto_goTypes,
		DependencyIndexes: file_src_taskTracker_proto_depIdxs,
		MessageInfos:      file_src_taskTracker_proto_msgTypes,
	}.Build()
	File_src_taskTracker_proto = out.File
	file_src_taskTracker_proto_rawDesc = nil
	file_src_taskTracker_proto_goTypes = nil
	file_src_taskTracker_proto_depIdxs = nil
}
